### ISSUE TITLE
Мигание окна

### ISSUE THREAD

**Issue by abbaabbbaabbbbbaa** [Grandbrain/NativeWPF#1]
Привет! Есть такая проблема. Если сделать такую разметку

```
<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>

        <StackPanel Width="250" Grid.Column="0"></StackPanel>
        <i:NativeWindow Grid.Column="1"></i:NativeWindow>
 </Grid>
```

то, при изменении размера окна программы, область в столбце 1 начинает моргать!

**Comment by lomakinandrei** [comment]
Полностью согласен, заметил это сразу после первого запуска. Устранить ошибку пока не получается, но идеи ещё не исчерпаны.

**Comment by lomakinandrei** [comment]
К сожалению, не смог устранить мигание при изменении размера окна. Скорее всего, это связано с внутренней "кухней" WPF, в таком случае ничего сделать не выйдет. Я улучшил код, вместо WinAPI и PInvoke использовал класс `WindowsFormsHost`. Мигание не изчезло, во всяком случае стало проще. Если появятся какие-нибудь идеи, можно продолжить обсуждение.
